config_setting(
    name = "wasm_runtime_wavm",
    values = {"define": "wasm_runtime=wavm"},
)

config_setting(
    name = "wasm_runtime_v8",
    values = {"define": "wasm_runtime=v8"},
)

config_setting(
    name = "wasm_runtime_wasmtime",
    values = {"define": "wasm_runtime=wasmtime"},
)
